/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3cd1deedceb75b5283af4494005ed9b1)
interface __BaseEnv_Env {
	ARTIFACTS: Artifacts;
	BROWSER: BrowserRun;
	AI: Ai;
	ASSETS: Fetcher;
	AGENT_MODEL: "claude-haiku-5-5";
	PREVIEW_WORKER: "thunderdome-sample";
	CF_ACCOUNT_ID: "bc1c0551f58de19c91a2d34f1a75e97c";
	PLAY_DAILY_LIMIT: "10";
	PLAY_INVITE: "";
	RACE_RETENTION_DAYS: "30";
	ADMIN_TOKEN: string;
	ANTHROPIC_API_KEY: string;
	CLOUDFLARE_PREVIEW_TOKEN: string;
	SANDBOX: DurableObjectNamespace<import("./src/index").ThunderdomeSandbox>;
	TASK_ROOM: DurableObjectNamespace<import("./src/index").TaskRoom>;
	RACE_INDEX: DurableObjectNamespace<import("./src/index").RaceIndex>;
	PLAY_QUOTA: DurableObjectNamespace<import("./src/index").PlayQuota>;
	JUDGE: Workflow<Parameters<import("./src/index").JudgeWorkflow['run']>[0]['payload']>;
	PUSH: Workflow<Parameters<import("./src/index").PushWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ThunderdomeSandbox" | "TaskRoom" | "RaceIndex" | "PlayQuota";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_MODEL" | "PREVIEW_WORKER" | "CF_ACCOUNT_ID" | "PLAY_DAILY_LIMIT" | "PLAY_INVITE" | "RACE_RETENTION_DAYS" | "ADMIN_TOKEN" | "ANTHROPIC_API_KEY" | "CLOUDFLARE_PREVIEW_TOKEN">> {}
}
