// Packs every app folder in demo/ into src/generated/sample-files.ts, so the Worker can seed
// Artifacts repos without a public git remote.
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const demoDir = join(root, "demo");
const outFile = join(root, "src", "generated", "sample-files.ts");
const SKIP = new Set(["node_modules", ".git"]);

async function walk(dir) {
  const files = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (SKIP.has(entry.name)) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(path)));
    else files.push(path);
  }
  return files;
}

const apps = {};
let count = 0;
for (const entry of (await readdir(demoDir, { withFileTypes: true })).toSorted((a, b) => a.name.localeCompare(b.name))) {
  if (!entry.isDirectory() || SKIP.has(entry.name)) continue;
  const appDir = join(demoDir, entry.name);
  const files = {};
  for (const path of (await walk(appDir)).toSorted()) files[relative(appDir, path)] = await readFile(path, "utf8");
  apps[entry.name] = files;
  count += Object.keys(files).length;
}

await mkdir(join(root, "src", "generated"), { recursive: true });
await writeFile(
  outFile,
  `// Generated by scripts/build-sample.mjs. Do not edit.\n` +
    `export const DEMO_APPS: Record<string, Record<string, string>> = ${JSON.stringify(apps, null, 2)};\n` +
    `export const DEFAULT_APP = "sample-app";\n` +
    `export const SAMPLE_FILES: Record<string, string> = DEMO_APPS[DEFAULT_APP]!;\n`,
);
console.log(`Packed ${Object.keys(apps).length} apps (${count} files) into ${relative(root, outFile)}`);
